### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aditi1403**
## Issue

[Grammatical edits in README.md file](URL)

### Issue Type

* [ ] bug
* [ ] task
* [x] improvement
* [ ] story
* [ ] epic

## Changes

*
*

### Additional Details

...

## Integration Tests

Do ITs exist that will test these changes?

* [ ] no
* [ ] yes
* [ ] this PR adds new ITs

## Postman

Do your changes include new or modified API calls?

* [ ] no
* [ ] yes

If yes, has the Postman collection been updated?

* [ ] no
* [ ] yes
* [ ] not applicable

## Documentation

Do your changes require a change to the documentation?

* [ ] no
* [ ] yes - internal
* [x] yes - external

### CODE REVIEW

**Comment by oo-0** [comment]
@aditi1403 Can you please give the complete readme a run of [grammarly.com](https://www.grammarly.com/)? We want to make sure your changes are grammatically correct.

**Comment by Manas-kashyap** [comment]
@aditi1403 is it now okay and ready to be merged ?

**Comment by aditi1403** [comment]
> @aditi1403 is it now okay and ready to be merged ?

Yes

**Comment by sonumehrotra** [comment]
@aditi1403 , good to be merged? Is the content all updated?

**Pull request merged**
